[metadata]
name = proc-utils-AI
version = 0.1.0
author = Zaman Huseyinli
author_email = admin@azccriminal.space
description = AI-powered process and CPU utility tools
long_description = file: README.md
long_description_content_type = text/markdown
license = GPL-2.0-only
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v2 (GPLv2)
    Operating System :: POSIX :: Linux

[options]
packages = find:
python_requires = >=3.8
install_requires =
    pyttsx3
    psutil
    PyYAML
    watchdog
    matplotlib
    seaborn
    numpy
    torch
    scikit-learn
    pandas
    tensorflow

[options.entry_points]
console_scripts =
    ai-cpufregd = cbinder_gbfs.ai_cpufregd:main
    ai-voicer = cbinder_gbfs.ai_voicer:main
    ai-analyzer = cbinder_gbfs.ai_analyzer:main
    cpu-mapping-visualizer = cbinder_gbfs.cpu_mapping_visualizer:main
    ai-lfs = cbinder_gbfs.ai_lfs:main
    train-ai-model = cbinder_gbfs.train_ai_model:main
    ai-affinity = cbinder_gbfs.ai_affinity:main
    simulate-io-stats = cbinder_gbfs.simulate_io_stats:main
    ai-greeting = cbinder_gbfs.ai_greeting:main
    quantize-model = cbinder_gbfs.quantize_model:main
    ai-dev-setup = cbinder_gbfs.ai_dev_setup:main
    ai-webops = cbinder_gbfs.ai_webops:main
    ai-agent = cbinder_gbfs.ai_agent:main
    ai-web-agent = cbinder_gbfs.ai_browser_agent:main
    ai-monitor = cbinder_gbfs.ai_monitor:main
    ai-backup = cbinder_gbfs.ai_backup:main
    ai-logs = cbinder_gbfs.ai_logs:main
    ai-dashboard = cbinder_gbfs.ai_dashboard:main
